# Generated by Django 4.1.5 on 2023-01-31 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_movie_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(upload_to="movie_images"),
        ),
    ]
